use_frameworks!

platform :ios, '9.0'

target 'LSJHAudioRecoder_Example' do
  pod 'LSJHAudioRecoder', :path => '../'

  target 'LSJHAudioRecoder_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
